name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Performance tool install
      run: dotnet tool install -g BenchmarkDotNet.Tool && cd $(ls -d */|head -n 1) && dotnet run -c Release -- --filter *Sum* --keepfiles && cd ..
    - name: Debug
      run: tree && ls ./MyBenchmarks/MyBenchmarkDotNet.Artifacts/results/MyBenchmarks.Md5VsSha256-report.csv
    - name: Test
      uses: ./dotnet-performance-action
      with:
        performance-report: ./MyBenchmarks/MyBenchmarkDotNet.Artifacts/results/MyBenchmarks.Md5VsSha256-report.csv
